const items = [
    {
        id: '001',
        image: 'images/1i.jpg',
        company: 'Himalaya',
        item_name: 'Purifying Neem Face Wash (150)ml',
        original_price: 225,
        current_price: 203,
        discount_percentage:9.77,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2i.jpg',
        company: 'Himalaya',
        item_name: 'Herbals Natural Glow Kesar Face Cream (25 g)',
        original_price:130,
        current_price: 96,
        discount_percentage:26.15,
        return_period: 12,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/3i.jpg',
        company: 'Himalaya',
        item_name: 'Nourishing Skin Cream',
        original_price: 95,
        current_price: 86,
        discount_percentage:10,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/4i.jpg',
        company: 'Himalaya',
        item_name: 'Tan Removal Orange Face Scrub(100g)',
        original_price:200,
        current_price: 164,
        discount_percentage:18,
        return_period: 12,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/5i.jpg',
        company: 'Himalaya',
        item_name: 'Nourishing Face Moisturizing Lotion(100ml)',
        original_price: 100,
        current_price: 88,
        discount_percentage: 12,
        return_period: 10,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6i.jpg',
        company: 'Mama Earth',
        item_name: 'Rice Face Wash for Glass Skin - 150 ml',
        original_price: 399,
        current_price: 339,
        discount_percentage:15,
        return_period: 14,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7i.jpg',
        company: 'Mama Earth',
        item_name: 'Vitamin C Daily Glow Face Serum for Radiant Skin - 30 ml',
        original_price: 399,
        current_price: 339,
        discount_percentage:15,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8i.jpg',
        company: 'Mama Earth',
        item_name: 'Vitamin C Daily Glow Sunscreen for Sun Protection & Glow - 50 g',
        original_price:349,
        current_price: 314,
        discount_percentage:10,
        return_period: 12,
        delivery_date: '1 Jan 2025',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
    ,
        {
            id: '009',
            image: 'images/9s.jpg',
            company: 'WoW',
            item_name: 'Ubtan Foaming Face Wash For Glowing Skin - 150 ml',
            original_price: 399,
            current_price: 380,
            discount_percentage:5,
            return_period: 14,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 4.5,
                count: 1400,
            },
        },
        {
            id: '010',
            image: 'images/10s.jpg',
            company: 'WoW',
            item_name: 'Apple Cider Vinegar Foaming - No Parabens, Sulphate Face Wash  (150 ml)',
            original_price:390,
            current_price:339,
            discount_percentage:15,
            return_period: 12,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 4.3,
                count: 24,
            },
        },
        {
            id: '011',
            image: 'images/11s.jpg',
            company: 'WoW',
            item_name: 'Vitamin C & Niacinamide (30 ml)',
            original_price:899,
            current_price:599,
            discount_percentage:33,
            return_period: 12,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 4.1,
                count: 249,
            },
        },
        {
            id: '012',
            image: 'images/12s.jpg',
            company: 'Pilgrim',
            item_name: 'Vitamin C Face Serum-30 ml',
            original_price:545,
            current_price:368,
            discount_percentage:38,
            return_period: 10,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 5.0,
                count: 10,
            },
        },
        {
            id: '013',
            image: 'images/13s.jpg',
            company: 'Pilgrim',
            item_name: 'Ceramides Moisturizer for Face 100g ',
            original_price: 395,
            current_price: 299,
            discount_percentage: 24,
            return_period: 14,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 4.2,
                count: 3500,
            },
        },
        {
            id: '014',
            image: 'images/14s.jpg',
            company: 'Pilgrim',
            item_name: 'Squalane Glow Moisturizer - 50 g',
            original_price: 550,
            current_price: 353,
            discount_percentage:41,
            return_period: 14,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 0.0,
                count: 0,
            },
        },
        {
            id: '015',
            image: 'images/15s.jpg',
            company: 'Cetaphil',
            item_name: 'Daily Facial Cleanser',
            original_price: 888,
            current_price: 887,
            discount_percentage:1,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 4.2,
                count: 388,
            },
        },
        {
            id: '016',
            image: 'images/16s.jpg',
            company: 'Cetaphil',
            item_name: 'Moisturizing Cream',
            original_price:1299,
            current_price: 1078,
            discount_percentage:17,
            return_period: 12,
            delivery_date: '1 Jan 2025',
            rating: {
                stars: 4.2,
                count: 5200,
            },
        }
    ];